### ISSUE TITLE
Double Clicking to Search

### ISSUE THREAD

**Issue by lab596** [Polyratings/polyratings#102]
I noticed that when searching for a specific professor utilizing the search bar it requires two clicks of the 'Enter' button. One closes the suggestion box and the second conducts the search. 

I was wondering if this was intentional. It would be a much appreciated quality of life change to have both of these actions completed in a single click of 'Enter' when a user is at the searchbar.

**Comment by JimmyChin946** [comment]
I noticed this as well. It seems to only happen with the search bar on the home page.

**Comment by mfish33** [comment]
Thank you! That is definitely a bug. I do not know when I will get a chance to fix this but this is a great first issue if you are interested in contributing.  The problematic code will be in `packages/frontend/src/components/SearchBar.tsx` or `packages/frontend/src/components/AutoComplete.tsx`. No pressure to contribute but it is always great to get new folks involved

**Comment by lab596** [comment]
Hey, I would love to contribute and will definitely look into it.
