### ISSUE TITLE
Accessibility Rating Feature

### ISSUE THREAD

**Issue by floresig** [Polyratings/polyratings#44]
Hey! Disability Alliance is trying to get this added to the formal professor evals, but it would be awesome to have accessibility as one of the things students can rate on. Things like whether professors post slides, have a hybrid option, flexible attendance,  whether they comply with DRC accommodations, stuff like that. It'd be great for people to know about stuff like that before they get stuck in a class with a terrible professor. Especially with COVID cases going up again.

**Comment by Mustardseed7** [comment]
As a fellow disabled student, I second this! Adding the option to rate the accessibility of a professor's course would be incredible. Having to sign up for classes with zero idea of whether a professor allows flexible attendance, honors DRC accommodations, gives ample time to complete assignments, upload accessible PDFs, etc puts us disabled students in a really difficult position, so having this added to Poly Ratings would be extremely helpful.

**Comment by mfish33** [comment]
I really like the idea of this! I think this would be able to make a good positive impact. This would definitely not be an overnight feature but I think it would be great to add to the website. To proceed, we would need to figure out how exactly this feature would work. Some questions:

1. Should this be separate from the normal evaluation form?
2. What criteria would we like to collect and the most effective way of displaying it?
3. Should this be an aggregate or a per rating basis. Similar to the existing metadata (ex. grade and postdate)?

I can think about some of these questions and try to come up with something but it would also be great to hear from you to gain more perspective.

**Comment by Mustardseed7** [comment]
Thank you for your consideration and for wanting feedback! I've spoken with other members of the Disability Alliance and we're working to put together feedback for you. Would you be available to Zoom/talk on the phone briefly? I'd like to ask a few clarifying questions so that I can make sure we understand what your questions mean? My email is: haheath@calpoly.edu 

Thank you!

**Comment by AddisonTustin** [comment]
Hi @Mustardseed7 we'd be happy to have a discussion about how we might be able to integrate this with the development of the site! I'll shoot you an email shortly with @mfish33 added so we can try to setup a time to talk.

Looking forward to seeing how we can keep helping students together!

**Comment by AddisonTustin** [comment]
Had some great discussions earlier in May. Some suggestions we received on the types of criteria we would be adding to the evaluation form would potentially look something like this:
1. Honors DRC Accomodations
    1. Scale 1-4
1. Accessible Course Policies (these might take form of tags or checkboxes that indicate a professor's policies). Though some of these are mutually exclusive, so perhaps a Y/N might be better form.
    1. Flexible Attendance Policies
    2. Inflexible Attendance Policies
    3. Zoom Office Hours
    4. No Zoom Office Hours
    5. Breaks During Lecture
    6. No Breaks During Lecture
    7. Pop Quizzes
    8. No Pop Quizzes
1. Class Materials Uploaded to Canvas (likely a similar format to "Accessible Course Policies")
    1. Accessible PDFs
    2. Inaccessible PDFs
    3. Accessible Slides
    4. Inaccessible Slides
    5. Captioned Videos
    6. Uncaptioned Videos
    7. Class handouts

**Comment by floresig** [comment]
This sounds great! Thanks for your work on this!! I think you should add whether slides/handouts/lectures are posted on Canvas, too. Especially since that'd be helpful for all students.
