### ISSUE TITLE
Migrate Old/Invalid Department Codes

### ISSUE THREAD

**Issue by AddisonTustin** [Polyratings/polyratings#5]
## Summary
There exist some professors in the Polyratings DB that are listed under the incorrect department. Either the department no longer exists, or it was just incorrect when the professor was added. When trying to get/return these professors, we fail validation because the department stored in the database is not in the actual list of valid departments at Cal Poly.

## Departments to Migrate
* Migrate Professors in the "IT" department to "ITP"
* Migrate Professors in the "PE" department to "KINE"

## Definition of Done
* Remove the invalid department from all professors in the Polyratings DB and replace that with the valid department (In both masterlist and individual professors.
* Replace the invalid department in the `courses` field of each professor and in the `reviews` keys of each professor as well.

[Example Professor](https://polyratings.com/eval/1352/index.html)

**Comment by mfish33** [comment]
In the definition of done, it takes about changing the department in the courses field as well as the department field. I feel that we should only update the department field as the courses did happen but the professors department is now equivalent to blank.
